display_name: LiClash
package_name: LiClash
maintainer:
  name: appshub
  email: appshubcc@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - LiClash
  - Clash
  - ClashMeta
  - Mihomo
  - Proxy

generic_name: LiClash

categories:
  - Network

startup_notify: true